sudo: false
language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      libdb-dev
      lighttpd
install: pip install tox-travis
script: tox && tox -e upload_coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
