sudo: false
language: python
python:
- '2.7'
- '3.6'
addons:
  apt:
    packages: libdb-dev
install: pip install codecov tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  on:
    branch: master
    tags: true
  user: sio2project
  password:
    secure: ORUaWHmji5JAxtVlDAUEEQfgg4OgCkYw2R2xOtpJqqCoBihPeCi7GBRTaswlLp44GICdvUEHa6iwnInwCniuDJ3D3TO5Kno3u1OFboetBS4aGWdttaHQUiqmNIX5OZCy+/MG9lQpXW3rKGRnFP3TRMzX7jlzJhHdSjljcuYBZmd5lzFbUvQmI0VA6+s61tduJWjl8EJpKE+cmr9xNXgWw3OVneKo7yoTyRcPEyMEzM+mXiTFrxqVxrsKjlj+e987pceEENDJ9+RGWj2DyAKE95To1YdRz1lvpRZHZ4P635UjFe8g1AbHyuKACCCGvikUuRRMlQrm5nxExKEniyTYcJ3l5T79rPhmQ0pn4ATMzEzzF9jyhlsNAsFNqQ4RoIYV1hV/xcwg5kBcVbKCpSK5XE1m5T4LnKe98OYnkapNaOgwto63XP+ShX+2+VxIzVAgFqoGVcguWX5W99zxeOq1RwiFRrp+ghfXiRu1AcMfdnhUA6TQ85q/7dyYeqQXmqr2YtgZsRMP7r2+MPC/MC5s8FdmQOQ2TXWS4osGsugyqupqSmpNM1vcxNlWq/dbGwoignvvscXf+5DrQ+fehLZ3ATnbKdeRVfPHmdf2rPqexRgVVpFY3oNt1lyxHviGFWw/7k4OhCvZHqp+wHBAGmyVf7J+0JYfnDpQRXbnvePjVI0=
